services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgres/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=localhost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5


  web:
    container_name: www_quizze
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: >
      bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy


